### ISSUE TITLE
QT: mined blocks are not shown as "Pending" 

### ISSUE THREAD

**Issue by TheTDD** [ROIcoin/ROIcoin#29]
I have found that the value of mined blocks (transactions with 360 confirmation) is not shown in Pending on 1st Tab of the Wallet. Just the value of unconfirmed transaction with 6 confirmation is shown there. Can you please either count the value of pending mining blocks in the "Pending" row, or even better create another row "Mined" and show the value of mined blocks there. 

That will simplify the financial planning and future deposits to get easy know how much value of mined block is about to expect after complete confirmation process is done.

**Comment by ghobson2013** [comment]
Hi TheTDD, 

Pending is for spendable coins only. Received coins can be spent right away. Mined coins are not spendable until fully confirmed so that would be a new category.
I don't see the purpose of adding this new category, as we are planning to reduce block maturity down to 60 , to match what most pools expect. ( 360 was too long ).
