### ISSUE TITLE
lost coin

### ISSUE THREAD

**Issue by crtcoelho** [ROIcoin/ROIcoin#59]
Hello,

i had been talked with ghobson on discord and after try some action without sucesses he suggested me to open an issue here.

I've been mining Roi with my notebook since January 2018.
I really like the project and I've got a lot of publicity here in Brazil. But unfortunately, since I am not a user with a lot of technical knowledge, I did not realize that I needed to update my walet to version 1.1.6.000. And on 04/15 when I sent some Rois to Cryptohub I discovered that my wallet was not synchronizing with the blockchain. 

I downloaded the current wallet and apparently everything I've mined so far and deposited in the long run is in conflict. 

I follow those instructions:
Procedure to resync the blockchain:  "Backup your wallet.dat , remove your blocks and chainstate subfolder from %APPDATA%/Roicoin folder" 

With ghobson´help I start ROIcoin-qt with the -loadblock=bootstrap-1532018.dat flag.

<img width="954" alt="3-00-23hs" src="https://user-images.githubusercontent.com/38509872/38960219-ff4817a8-4339-11e8-8347-bf5d46033293.PNG">

But  when you see my transaction history there is just ONE transaction ok. All of the other (more than 50) if you click there is a message about a CONFLICT:

<img width="967" alt="4" src="https://user-images.githubusercontent.com/38509872/38960181-e473d868-4339-11e8-9790-31670216c275.PNG">

So ghobson asked I start ROIcoin-qt with the -rescan -zapwallettxes=2 and wait till I see in the debug.log "rescan    29333ms". But it did not appered and now my 256 806.62831275 Roi locked disaperd:

<img width="953" alt="6" src="https://user-images.githubusercontent.com/38509872/38960367-9f0fa9c2-433a-11e8-8d7b-65fc720bc163.PNG">

ghobson had suggested sending you my debug log:

[debug.log](https://github.com/ROIcoin/ROIcoin/files/1925947/debug.log)

If you think it is important I can send later blocks and chainstate subfolder that I removed following instructions.

Please let me know if i can give you more info.

Best,

Claudio Coelho

**Comment by DisasterFaster** [comment]
Claudio, whenever you mine or even just hold any coin it's very critical to stay abreast of wallet releases to avoid situations like this. In our best effort to keep the community informed we announce wallet releases at Facebook, Twitter, Google Plus, BitcoinTalk, Discord, Instagram, Telegram and the website. 

Because you were mining on the wrong chain with very little competition you were able to mine an enormous amount of coins as shown in your details above. Had you of been mining on the official chain and with recent hash rates being high the mining payout would have been a much lesser amount.

My best guess is you may have mined somewhere between 10-20 blocks. While I can't replace all of the coins mined on the wrong chain I am willing to send you an amount of coins that would represent what you may have mined had you been on the correct chain.

Please provide me with a proper wallet address and I will get those coins sent out right away.

**Comment by JonathanLS** [comment]
@ghobson2013 Hello Gary, Could you help me with the step "start ROIcoin-qt with the -loadblock=bootstrap-1532018.dat flag", please."? Let me explain. I was using the ROIcoin Core - Wallet 1.1.2.0, but after get some coins, I didn't used it anymore. I made up my mind to mine ROIcoin again, but it wasn't able to sync (it's stopped at block 68957, 8 weeks behind) , so I updated the wallet to version 1.1.6, did backup of my wallet.dat and removed the folders "blocks" and "chainstate' subfolder. After these steps I re-started the wallet and it synchronized with network 25 weeks behind. Unfortunately my Balance is showing a Total of 0.00000000 ROI. So, how I must execute the step "start ROIcoin-qt with the -loadblock=bootstrap-1532018.dat flag" and get my coins mined with version 1.1.2.0? P.S.: I am using Linux. My ROI address is RBPh9StNxna7xgHiXy9KPGeKuLW57ja7M4. Thank you in advanced.

**Comment by DisasterFaster** [comment]
Jonathan I just sent you 5000 coins to RBPh9StNxna7xgHiXy9KPGeKuLW57ja7M4 You can view it on the block explorer here: https://roi-coin-blockexplorer.roi-coin.com/address/RBPh9StNxna7xgHiXy9KPGeKuLW57ja7M4 I decided to send you twice as many coins as I told you a week ago to help compensate you on this. Best of luck!

**Comment by JonathanLS** [comment]
@DisasterFaster I really appreciate your decision, but I think you wanted send them to crtcoelho.

**Comment by crtcoelho** [comment]
I got it.

I´m travelling and as soon I came back to home I´ll provide  wallet address.

Best,
crtcoelho

2018-04-24 8:03 GMT-03:00 DisasterFaster <notifications@github.com>:
