### ISSUE TITLE
ROIcoin v1.2.0.000: it is not opening Links and Social Networks

### ISSUE THREAD

**Issue by JonathanLS** [ROIcoin/ROIcoin#72]
Hey Guys,

I have just installed the wallet ROIcoin v1.2.0.000. It is working fine, except the links and social menu options. When I try open a link or a social network it returns the error 

"Failed to run the default web browser. Input/output error."

I am using Linux Mint 18.3 and I have two web browsers: Google Chrome and FireFox.

Regards
JonathanLS

**Comment by ghobson2013** [comment]
Hi Jonathan
You will need to set your default web browser in system settings->details->application settings
QT5 is relying on xdg-settings to figure out your browser.

For me this works fine as long as you start ROIcoin-qt as the user you are logged into via the GUI.
So doing sudo for example in a terminal, wont work because xdg-settings don't get populated if you change user.

**Comment by JonathanLS** [comment]
I put Google Chrome as my default web browser. Restarted it and opened the wallet. Same error.
